---
step-runner-config:
  global-defaults:
    organization: redhat
    application-name: vcs-backend
    service-name: service
    container-image-repository: rhvcs/vcs-service

  generate-metadata:
  - implementer: Jenkins
  - implementer: Git
  - implementer: SemanticVersion

  tag-source:
  - implementer: Git
    config:
      git-username: rhvcs-monorepo-workflow

  create-container-image:
  - implementer: Buildah
