step-runner-config:
    tag-source:
    -   implementer: Git
        config:
            git-password: ENC[AES256_GCM,data:26tOt4P6T+HpXaoPSAa88Y2+RMo=,iv:Uuf0kYrHXusDZB6DcwqMmwC8bN5I5CNfIQuGDEfhErs=,tag:WFUr3VcjYjrHS8q1A30W6g==,type:str]
    deploy:
    -   implementer: ArgoCD
        config:
            git-password: ENC[AES256_GCM,data:1n6SHZvmCrslqSRz4JglbCR/ISU=,iv:Gbc3EhtZXlV/VTyltBpkcNkw6i18djSHVAY8TQ+v2hI=,tag:vHHj+rqSQ7bxSt+z8wpS3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-10-25T21:52:04Z'
    mac: ENC[AES256_GCM,data:cCWvPrdDi7vqD/GfHt9pGFjj3VRCe8f8+saOoAXN6Vy+aP+tZN85Qs0/W7oAUul16M6FZm8+Eh1daVUKuD6x4heJ04Qdac4mbA3gDdYLqUgdjsK19d2vcrKpA3+0BG6864SaqjxIbrX/NReYUXglcpWR0fggyeaAYroAkaO1Edg=,iv:XxrHtW9SFj2lpdexopnsKTRlQPQG202SwV1MIM0v3uo=,tag:/MzC5jAd8QI+O6BEo8+Crg==,type:str]
    pgp:
    -   created_at: '2021-10-14T21:41:00Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/pHJVB+8SuwARAAmj2lyR0OaWOmoKcTymAV2F1nhZ/e/RGTSkfIbp1B7KSt
            F6Ll48R5ZtKDcsyNIuhPf5q5RAL2jC+fxz1CPMhY7RIj2YPiDqXTxuQnMpcCdKAu
            WESNfmFPjB+pmaNefrPpfty4GG8K9LiYm7xLChq9Cg1qMd8IgXFnF5TY+0CyTiSF
            PbihE8vSPUXEhsueEhwd4fY+CWMPOv+GWktRNAqLEJpITErnNZyT78o7qNfooP7a
            tzoIElBLqBch32zXmN42XfbOispQgaGaN9k7qR3Cmd+H84Ny8ABjmkiIRC8bfQoB
            jOeumU2dew7BD1TM4ljnl5DTkMkli4WETVwN4Hk0x3k8K4XMqBuRaCHuxhQRBsC3
            YeteDg3ldwBBCEZ5KK0UqMx12MEjDVG+rgzpD1TP72pPxSRz+eLF0if3IJ9L2FIW
            wfklKBN1j4nBgABKJrePthZyy0UFjWeYzyEsfH1dOcOWLx8aGPmNQw2mIuNxuzop
            dGN+CRyhILLdXhgbpjBipzmqz+nBFZULQoOQLqBtN62HvRJlh0JCMdUVrWhP9C8+
            4zhS9aNKRYBVPXUfPsTPEQcXQD+I6sADxeUDOuBt0A6nAjcNixZOVrfGxAnaF4tV
            U4Uft4Sn6hvwErlSN4Eu/OV1CtXrT9vKTpnLHJioAxeqI2btAJ+NUPC5ewedSLTS
            XgG/Hd04YadqA5lxGlOkGcTnSO4RXCz2nd8ZNLFFQ+xmsdtKfpLrkvzPf4TTWD21
            L1bsQPvHZzWaQtDCCLkSjiCg4CWhN2y2O0gaxBI8ITzaS++gu69igMR0FcOQfaw=
            =EsE/
            -----END PGP MESSAGE-----
        fp: 355C11B55E83B15E5CF6366283637FAF9D7905E1
    -   created_at: '2021-10-14T21:44:34Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4cosCggMlEWAQ/+ISuDMIdoa1qfH/IEm2d8/nzUhlVtcWX6+EGWXsONE4gF
            MLqCA7Hvg3C42DwNZArYZW4+bdg/O51h5qEOXNweozbn7PEVQ28KKUqDcvQU1r/M
            O1lCWnH76sxs4I0+utFi8aA1DkcEA5YjbY5TGk6zImIAHMIzSm1f+62gvsldaRj5
            rLMdpDPcw0/v+LqP+9QnqMws73cbeUEo+2UYc3KRCykdGuhji1RkpsJa0D7313hF
            vHZ/8xPAHnRO5Lc/r+JNHIHE1r0s8W0dMKux4P9g0AfWFHnbTpGKvlnn3rmpLZ6C
            QY5oX97uoX+bHR2YGkdF52v763e7TTxJ6guukMdYOpk7LZUP61B0gxCQkR4RfzEp
            09t5LIrVFWNk011YPxpIhS8ODVA+3MUCXoWk+HWMKUD4EwZvJk0YJUPucHbAwxtk
            gUZLnUWtWGbJD01SEYnGKeebfNEHw5ZEJQxCXG2ehdGB7OjVzTCnJV8K7MsynwN+
            m7y3bXEzWYb+L2RGA/ikohB5gFZv2gID24LeIGiv0lVrEPdkUV5GJCMM5VX8HXeI
            2JtW0IoCoLA4RA1X02/8QXr48D45NK1mgxX62OgzGCm90yC0qOHUopkM5UXEIDQP
            mCPWGDH0WFMcfIDHvIpxur0+nI9yhxzjq+WYRPp51DkzHgIQH6QcxwnrIx8dqjfS
            XgFRFYb9UB9ItfkVrM7TEBM5RNljEcElqBpgWfoaR4tuhCAWgHJCbLw9EbLAkg78
            chTbmsg93cLuBQEyPFqxc6BRRxgBXcUXDRzc6obyKUgnYxcl5RWSNC9jXsQBl2k=
            =8tSD
            -----END PGP MESSAGE-----
        fp: 82CCC83BE58E7985C1FAD60399CA50E2B174AE29
    -   created_at: '2021-10-14T21:44:34Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4VALzX5s2x4ARAAt9KRBb16rSsAtQg9xJx6YVmdv57u32aUPXSSwJxm9And
            JjiIx9/az6u+y4IJpK4aaH1HZI8NOTyVwya2g7XoxK3qBGs1mE+AXf4smMohcCTX
            cN6TTbEVrOX8RgWSK59ydnbHtN3WYL0E/iNTB1S+Jv6uiY9pNLWicelyXpYF8SXJ
            FYCo0uo+RHbufgYSPI9BT5Q+WGOOtn7rcIu7MFLZ93rWg0lZYEkgCPDbKfLIUJUI
            Q65oyzyB/dK9rV0TEmCMRf64/tIqvFsfO6TLIU2JJI2mj2xcoX+ywhUA7YRgodnw
            a6C2CiNHvrV8Reo3mkGz68Rm5fnzS+gzrRIgJ+kdG33ykT8hUlGLOi56fp4VD1yk
            Lc17xyynGEPSg0z+tE5V2xU6aCT77lPkuKASeKProYE9vjfh91NfiS4WCZtjOXp4
            qqh2tLnqj78KDLOkioIlqquqXaItEDKG2hU7sYfHb6jCUoOxuocYsULG73yfHol2
            xYwo3yPMSt3MvXAYrLaM8jVFQoKnHeTMELPt3pHYbRUGarZ8hAVjmdCtvjuIhB/8
            ceYIKuv7CRLgcfd498ruij+73iVAy8NcOglj75x0b7c1vZx27ePS3QMeYXVdRw7b
            usymHdKj0FUQqeUxwKA/R04QxPJTB2UtGu5AwDKv7ITFzWBN94lkwzchl6ZQ04bS
            XgHAzoiS5iKfI+p3ztanRovUBhoXUHm3Q9OSJcaIrO/PaJPicGUGZJEpz+CpbMna
            nG5AGbsw3vplZb0seYwhTm/mr2Cr1r0RMy4qhQvH1XJOd8VZC7LjmtyTdQDp9fQ=
            =toLX
            -----END PGP MESSAGE-----
        fp: 8AE499DD092430C1E2DCE845E8F36B93FE52A6CF
    -   created_at: '2021-10-14T21:44:34Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzlTOzb6XH5MARAAuKyc8aNNVj/2puS7wgRnMlFTbtHlafPB++mh6+iUwcoL
            SNCUF9hFSRv2t8/faVXPptrMCcQvYau5R2UDM+Y3INJM5Wtb1ys/vXiXUSMp2Kdv
            dPgF7QSteQn+H3koVPw/fu+WmzelkEpy/hKgeOj5qurnSLCCMTZRBmPb5Fj1nhIF
            E4p9CON5B7o3F34CjQTw8oLJG6Wdc+z9zqiqtmt02PVbl6l8I8h+9ibChYt/3dtP
            kzZLD1iG/tWZgbQsgyfwLGe3vD6Khzlz1XpQkm3a0K3fAb6OKhHk44cBTjDf1JCH
            /u18HdUE05YqY3iU3JJMuu+imDMka61C1Ck2tCXHi7v1QwFGKKDTHh+DUUin1EG8
            sVMijq4dHRLspEn8LEXtILyJxUPBuMQhdubc4vMuwGq7eNSqeNYLd4yeKoxgc5QR
            kY12kKrGn50Ly3918qLKq3h20muLLk1aOnVpD9osmF27aSGG+5caEzZplUXmBypo
            HiO7NEIaBJos0Ziz+0WJFpQxoEtLYFvccU3dccJi4Ern3pyh6vMCdBIplcxLE5Od
            ArcGCqVUzvTKz3lHsIHvAuZak0hRocJM9ng7qrzj9FssToFS6IfvTn3qnZIHEeVJ
            Vt23Vh439dbg95HzEVMCD6VW8xItZQv0nxoz42FndNlVocQlks08PaMK+CBu08DS
            XgFikqc1ilTEKbI5Qy2sYJ76dUHBpKrJ8/eed5Vg5lkrRm2J9X4UrqobPpuT6uDz
            wjVTwCjl/WYbJ2CDDd8W3s0HuUfEPxjRMK6n/qcIecelQbLbNQcLkD8ngfZRibI=
            =dcQy
            -----END PGP MESSAGE-----
        fp: 2DBD7652E666814AD25711B1A6ADB6AA81DAB7B8
    -   created_at: '2021-10-14T21:45:27Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxWhoUZAfyGVAQ//fswEVfUPT5zQGHjEIlV21OnSJtpmFWv3SxmP7WLklcEN
            jcDSHjfX/jsM1LVxnTkbQmB5+mfsGD5iMbJ03kfvK/VpVwp+kIzEOcvdgQ1JiYC4
            CurNxEzWEYb20ZdIhU/l5LBTv4K1SRZTrm3KY7M0OdioaAGAvp0lgBNvsh9Iv49C
            M28wsU2EjZEBjymFOsYx9Zcp/Eh24xsEVKCg9ve+Yu64ge/aTrpLdmUeQd5pkBW2
            7jvPcnUaSi1lGC4NlheWpB/AJZdsDBa4vdJKrxYoUEJpbH1t7KpGvvoCQYiFod2u
            37MZ6VaH6tKAhss8D5ul87WfK7OVyibaH13txr6bnJnYfZS34v0IiBToqGq9JVxR
            rKKLSkS/RIX1/kKQPBj5iU+M7omQKnEyIsYXRIEyR2j49hhFnsVrQL8wiRkPIh4a
            /fzMi3ycr4TJv+VUiV3NIE7F9KOCQxgLwbI+JraR3OvTG8JcUhmtN5Qiwkq8KeWm
            GIi+dYShyqHRStWqnomqkoGt4KyhOZO42Kuk+uT7ZXLl1FsMPRoS9FP7i0Tzw6Tg
            SBm3InyCJh2g/ntlYD4sIP9iVHHtnxTDB370vSxB/CFH28XpNGKg9PNkIqWtcXAu
            0rjKbrhJP4jzJiKNu0aK8pY4wEDPZcz7KUCRZoktkbZdEFECz3Leswb8PymXBlrS
            XgGU9WgbMBrAakUHg76dATiDarKzaBYZZRwA/U9L39iOkL5WgZufblxvtPg/bCuQ
            w+bz1HnQOlr7SYQ1YDgXwCzIus4tZHUP23KemMZntOBfpTPowc/6dUGJuNOdqZs=
            =gyiX
            -----END PGP MESSAGE-----
        fp: C0D9573DD441156D1A82B6FEED3EEE5904206977
    -   created_at: '2021-10-20T19:27:00Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1j1M1wGETuWAQ//aIycf2lkph1Oc+Q5IcVm5wtT9NInR9dhi/49MR10GprE
            2BX4A5vT6n6jDHb2XbjbX0r3Rt526XDV1bxgDxczPFcRSiLPFZokHjJGrf/hSxhr
            xUf/0IBw0IboqjuIk3d7QsW69ettA3w0Xa4qsNObQPl187CUAjpLp6Bj0wxAVO1o
            QFJxpnjxF0D4pN34W7JbxPJIv5bNbRfJlbcnQgc3sIvSNrjoyYkzBQz5hHG9OJzf
            bxnc7X0eT0lQq9HQafDFTAt7r0Xf5vTJe4hhWWmT5DoK4gKxvRgDOU6TwjWhmrPH
            RQgDHInbl5eU2RVebwZYVO9MUEQDcVl2u87QIwtX0r5iXVb4sTUwWQxjGDGon+TP
            obya81xdYSYps99v+zahw5DhzWduE2c0Pj7aXGHSN2Pj67LO3RKvlNEL31RMb4zy
            bR2LOg7nENofNSP+6bt36kQLHTak1kkNKesY9DICRBnIV4X7CdjsNhaAwidyDGEt
            hzJJoQIe0dAs3BjCOh/3jWdQT5iJjJWehusSADoomb9gOrgDOV7tfyIxgEHmj7Zu
            Y0Uwqv3YR3/i5EijC3/voWOizO/0Oqq1l4e3xt0XEJowCbS1VNbm9P0VZEECTj6q
            3jsWXFFQg76etLPhc9pkW5vQPNkktlUZCHvp0oJ7uJq5GeeQ6tb7kKLmTnvMFVLS
            XgH/1rH6SuvWMv3jYpP98sJB3USfwb8dtxzRML6HMpWJcnadoCE8T3Nrb1Fx/dwI
            lAQuyarLYT4e4u7z1Bp58TFpFE1SVb5QVSzou/OCXDhTj4PWHlvB0mxNJ2JK5Ag=
            =n+n2
            -----END PGP MESSAGE-----
        fp: 1D680E552A5E0A5FEAAA25797FC30FE4DF65B0D0
    unencrypted_regex: ^(implementer|name)$
    version: 3.7.1
