---
step-runner-config:
  global-defaults:
    organization: redhat
    application-name: vcs-argocd-cleanup
    service-name: service
    container-image-repository: rhvcs/vcs-argocd-cleanup


#TODO - implement semantic version
  generate-metadata:
  - implementer: Jenkins
  - implementer: Git
  - implementer: SemanticVersion
  - implementer: Npm

  tag-source:
  - implementer: Git
    config:
      #git-username: rhvcs-monorepo-workflow
      git-username: kharyam

  create-container-image:
  - implementer: Buildah
